language: ko
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    ruff:
      enabled: false
    shellcheck:
      enabled: false
    biome:
      enabled: false
    markdownlint:
      enabled: false
    hadolint:
      enabled: false
    swiftlint:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: false
    gofmt:
      enabled: false
    sqlfluff:
      enabled: false
    checkov:
      enabled: false
    detekt:
      enabled: false
    phpstan:
      enabled: false
  path_filters:
    - "**/*.java"
    - "**/*.kt"
    - "**/build.gradle"
    - "**/build.gradle.kts"
    - "**/application.yml"
    - "**/application.yaml"
    - "**/application.properties"
  path_instructions:
    - path: "**/*Controller.java"
      instructions: |
        - HTTP 메서드와 엔드포인트 설계의 RESTful 준수 여부를 확인해주세요
        - 요청/응답 DTO의 적절성을 검토해주세요
        - @Valid, @Validated 어노테이션 누락 여부를 확인해주세요
        - 예외 처리가 적절한지 검토해주세요
        - Controller는 요청 검증과 Service 호출만 담당하는지 확인해주세요 (SRP)
        - 불필요한 비즈니스 로직이 포함되어 있지 않은지 확인해주세요
        - API 응답 포맷이 프로젝트 전반에서 일관적인지 확인해주세요
        - 공통 응답 객체(ApiResponse, CommonResponse 등) 사용 여부를 검토해주세요
        - 성공/실패 응답 구조가 통일되어 있는지 확인해주세요
    - path: "**/*Service.java"
      instructions: |
        - 비즈니스 로직이 명확하고 단일 책임 원칙을 따르는지 확인해주세요 (SRP)
        - @Transactional 어노테이션의 적절한 사용 여부를 검토해주세요
        - 트랜잭션 범위가 필요 이상으로 크지 않은지 확인해주세요
        - Service 계층에서 영속성 계층(Repository)에 대한 의존성이 인터페이스를 통해 이루어지는지 확인해주세요 (DIP)
        - 하나의 메서드가 너무 많은 책임을 가지고 있지 않은지 확인해주세요
        - 핵심 비즈니스 로직에 대한 테스트 코드 존재 여부를 확인하고, 없다면 테스트가 필요한 이유를 간단히 언급해주세요
    - path: "**/*Repository.java"
      instructions: |
        - N+1 쿼리 문제가 발생할 수 있는 코드를 확인해주세요
        - fetch join, @EntityGraph 등의 적절한 사용을 검토해주세요
        - Lazy Loading 전략이 적절한지 확인해주세요
        - 불필요한 즉시 로딩(EAGER)이 있는지 확인해주세요
        - 커스텀 쿼리의 성능과 정확성을 검토해주세요
        - 복잡한 쿼리 로직의 경우 테스트 코드 존재 여부를 확인해주세요
    - path: "**/build.gradle"
      instructions: |
        - 중복된 의존성이 있는지 확인해주세요
        - 잘못된 spring-boot-starter 조합이 있는지 검토해주세요
        - 버전 충돌 가능성이 있는 의존성을 확인해주세요
        - 불필요한 의존성이 포함되어 있지 않은지 검토해주세요
        - 보안 취약점이 알려진 구버전 라이브러리 사용 여부를 확인해주세요
    - path: "**/*Entity.java"
      instructions: |
        - 연관관계 매핑의 적절성을 검토해주세요
        - Lazy/Eager 로딩 전략이 적절한지 확인해주세요
        - 양방향 연관관계의 경우 주인(owner) 설정이 올바른지 확인해주세요
        - cascade 옵션이 적절한지 검토해주세요
        - orphanRemoval 사용이 적절한지 확인해주세요
    - path: "**/*Dto.java"
      instructions: |
        - Validation 어노테이션이 적절히 사용되었는지 확인해주세요
        - DTO가 단일 목적만 가지는지 확인해주세요 (SRP)
        - 불필요한 필드가 노출되고 있지 않은지 검토해주세요
    - path: "**/*Config.java"
      instructions: |
        - 보안 설정(SecurityConfig 등)에서 인증/인가 누락이 없는지 확인해주세요
        - CORS 설정이 과도하게 허용적이지 않은지 검토해주세요
        - 환경별 설정 분리가 적절한지 확인해주세요
chat:
  auto_reply: true
tone_instructions: |
  - 공손하고 협력적인 톤을 유지해주세요
  - 문제를 지적할 때는 개선 방향을 함께 제시해주세요
  - "~하는 것이 좋을 것 같습니다", "~를 고려해보시면 어떨까요?" 같은 제안형 표현을 사용해주세요
  - 코드 작성자의 의도를 존중하며 건설적인 피드백을 제공해주세요
  - SOLID 원칙 위반 시 어떤 원칙을 위반했는지 명확히 설명하고, 개선 방안을 제시해주세요
  - 심각한 보안 이슈나 성능 문제는 우선순위를 높여 강조해주세요
guidelines:
  - 주니어 개발자가 이해할 수 있도록 문제가 발생하는 배경과 원인을 간단히 설명해주세요
  - 해결책을 제시할 때는 "왜 이렇게 해야 하는지" 이유를 함께 설명해주세요
  - 가능하면 간단한 예시 코드나 비유를 들어 설명해주세요
  - 용어를 사용할 때는 간단한 부연 설명을 추가해주세요 (예: "N+1 문제(연관된 데이터를 조회할 때 불필요한 쿼리가 반복 실행되는 문제)")
  - 테스트가 필요한 핵심 비즈니스 로직인지 판단하고, 테스트 부재 시 테스트가 필요한 이유를 간단히 언급해주세요